### ISSUE TITLE
Traceback (most recent call last):   File "xmlrpc-bruteforcer.py", line 227, in <module>     main()   File "xmlrpc-bruteforcer.py", line 204, in main     queue = reader(wordlist, chunks_size, verbose)   File "xmlrpc-bruteforcer.py", line 162, in reader     chunk = list(islice(wordlist, chunks_size))   File "/usr/lib/python3.8/codecs.py", line 322, in decode     (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte

### ISSUE THREAD

**Issue by subhash0x** [aress31/xmlrpc-bruteforcer#7]
Traceback (most recent call last):
  File "xmlrpc-bruteforcer.py", line 227, in <module>
    main()
  File "xmlrpc-bruteforcer.py", line 204, in main
    queue = reader(wordlist, chunks_size, verbose)
  File "xmlrpc-bruteforcer.py", line 162, in reader
    chunk = list(islice(wordlist, chunks_size))
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte

**Comment by Reelix** [comment]
Confirmed - Happens when trying to use rockyou as a wordlist

**Comment by prykon** [comment]
Just pushed a fix. Waiting for merge.

**Comment by prykon** [comment]
@aress31 We can close this issue now. :)
